version: '3.9'
services:
  api:
    build: ./api/labrary-manga-api
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=library;Username=postgres;Password=postgres
    depends_on:
      - db
  front:
    build: ./front
    ports:
      - "8080:8080"
    volumes:
      - ./front:/app
      - ./front/dest:/app/dest
      - ./front/node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init/:/docker-entrypoint-initdb.d/:ro
volumes:
  pgdata:
